---
name: Develop Branch Workflow
on:
  push: # Trigger the workflow on push to develop branch
    branches:
      - develop # should be the default branch in your repository
      # Conditions:
      # Require a pull request before merging
      # Lock branch
      # Require conversation resolution before merging
  workflow_dispatch: # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        echo "Triggers a deployment to the development environment"
