---
name: Release Branch Workflow
on:
  pull_request: # Trigger the workflow on pull request to main branch
    branches:
      - main # Should use the rebase and merge strategy
  workflow_dispatch: # Trigger the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        echo "Triggers a deployment to the acceptance environment"
